static_transform_publisher:
  ros__parameters:
    frame_id: "base_link"
    child_frame_id: "camera_link"
    translation_x: 1.0
    translation_y: 2.0
    translation_z: 3.0
    rotation_x: 0.0
    rotation_y: 0.0
    rotation_z: 0.0
    rotation_w: 1.0
