services:
  ros2:
    build: .
    tty: true
    privileged: true
    network_mode: "host"
    pid: "host"
    volumes:
      - ./ros_ws:/root/ros_ws
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/admin/.Xauthority:rw
      - /etc/localtime:/etc/localtime:ro
      - /usr/bin/tegrastats:/usr/bin/tegrastats
      - /tmp/:/tmp
      - /usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra
      - /usr/lib/aarch64-linux-gnu/tegra-egl:/usr/lib/aarch64-linux-gnu/tegra-egl
      - /usr/src/jetson_multimedia_api:/usr/src/jetson_multimedia_api
      - /opt/nvidia/nsight-systems-cli:/opt/nvidia/nsight-systems-cli
      - /usr/share/vpi3:/usr/share/vpi3
      - /dev/input:/dev/input
        # - /run/jtop.sock:/run/jtop.sock:ro
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - FASTRTPS_DEFAULT_PROFILES_FILE=/usr/local/share/middleware_profiles/rtps_udp_profile.xml
      - ROS_DOMAIN_ID=2


