recorder_params_node:
  ros__parameters:
    use_sim_time: false
    record:
      is_discovery_disabled: false
      topic_polling_interval:
        sec: 0
        nsec: 10000000
      include_hidden_topics: false
      ignore_leaf_topics: false
      start_paused: false
      topics: 
        - "/tf"
        # - "/camera/depth/image_rect_raw"
        # - "/camera/depth/camera_info"
        
    storage:
      uri: "/root/ros_ws/bag_files/tmp"
      storage_id: "sqlite3"
      max_cache_size: 20000000