analyzers:
  ros__parameters:
    path: "vicon_analyzers"
    analyzers_group:
      type: diagnostic_aggregator/AnalyzerGroup
      path: "analyzers"
      analyzers:
        vicon:
          type: diagnostic_aggregator/GenericAnalyzer
          path: vicon
          startswith: ["vicon_bridge", ]
