analyzers:
  ros__parameters:
    path: "vslam_analyzers"
    analyzers_group:
      type: diagnostic_aggregator/AnalyzerGroup
      path: "analyzers"
      analyzers:
        frequency:
          type: diagnostic_aggregator/GenericAnalyzer
          path: frequency
          startswith: ["frequency_monitor", ]
          find_and_remove_prefix: ["frequency_monitor" ]
        vslam:
          type: diagnostic_aggregator/GenericAnalyzer
          path: status
          startswith: ["vslam_monitor", ]
          find_and_remove_prefix: ["vslam_monitor", ]
