# define the topics to monitor
topics:
  - camera_infra1:
      topic_name: "/camera/infra1/image_rect_raw"
      topic_type: "sensor_msgs/msg/Image"
      min_frequency: 55.0
      max_frequency: 65.0
      #- camera_infra2:
      #    topic_name: "/camera/infra2/image_rect_raw"
      #    topic_type: "sensor_msgs/msg/Image"
      #    min_frequency: 55.0
      #    max_frequency: 65.0
      #- camera_splitter_infra1:
      #    topic_name: "/camera/realsense_splitter_node/output/infra_1"
      #    topic_type: "sensor_msgs/msg/Image"
      #    min_frequency: 25.0
      #    max_frequency: 35.0
  - vslam_status:
      topic_name: "/visual_slam/status"
      topic_type: "isaac_ros_visual_slam_interfaces/msg/VisualSlamStatus"
      min_frequency: 25.0
      max_frequency: 35.0
